runtime: nodejs
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
vpc_access_connector:
  name: projects/cute-project-730912/locations/us-east1/connectors/cute-connector
